package com.free.ping.configuration.response;

public interface Message {
    String PING_TITLE_REQUIRED             = "PING_TITLE_REQUIRED";
    String PING_PING_URL_REQUIRED          = "PING_PING_URL_REQUIRED";
    String PING_SLOW_DOWN_SECONDS_REQUIRED = "PING_SLOW_DOWN_SECONDS_REQUIRED";
    String PING_SLOW_DOWN_SECONDS_INVALID  = "PING_SLOW_DOWN_SECONDS_INVALID";
    String PING_INTERVAL_REQUIRED          = "PING_INTERVAL_REQUIRED";
    String PING_INTERVAL_INVALID           = "PING_INTERVAL_INVALID";
    String INCIDENT_OF_REQUIRED            = "INCIDENT_OF_REQUIRED";
    String INCIDENT_TYPE_REQUIRED          = "INCIDENT_TYPE_REQUIRED";
    String INCIDENT_TYPE_INVALID           = "INCIDENT_TYPE_INVALID";
    String INCIDENT_OF_INVALID_FORMAT      = "INCIDENT_OF_INVALID_FORMAT";
    String INCIDENT_AT_INVALID_FORMAT      = "INCIDENT_AT_INVALID_FORMAT";
}
